name: Bug Report
description: Report a bug with Extendium itself (not a specific Chrome extension)
title: "[Bug] "
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Use this form for bugs with Extendium itself (UI, manager, backend, etc.).

      If the problem occurs only with one specific Chrome extension, please use the "Extension Issue" template instead.
- type: textarea
  attributes:
    label: Describe the Bug
    description: A clear and concise description of what you're experiencing. If applicable, add screenshots to help explain your problem.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Is this an Extendium bug (not extension-specific)?
    options:
      - label: This issue is not limited to a single Chrome extension
        required: true
- type: input
  attributes:
    label: Plugin Version
    description: What version of the plugin are you running?
    placeholder: "e.g. v1.2.3"
  validations:
    required: true

- type: input
  attributes:
    label: Millennium Version
    description: What version of Millennium are you using?
    placeholder: "e.g. v2.17.2"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Operating System
    options:
      - Windows
      - Linux
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear and concise description of what actually happened.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Reproducibility
    description: Is this issue consistently reproducible?
    options:
      - label: Yes, I can reproduce this issue consistently
- type: checkboxes
  attributes:
    label: Troubleshooting tried
    description: Select all the steps you have already tried
    options:
      - label: Restarted Steam
      - label: Switched to Default skin/theme (only applicable if it's and UI issue)
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With these settings...
      3. Click '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs / Console output
    description: Paste any relevant logs from the console or logs directory.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Screenshots? Anything that will give me more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
