blank_issues_enabled: false
contact_links:
  - name: Millennium Support Server
    url: https://steambrew.app/discord
    about: "Need direct help? Join the Millennium Discord server and ask in the #extendium channel under plugin support!"